### PR TITLE
chore: Accommodate jwt's minor and patch updates

### PR DESCRIPTION
**Pull request by sato11**
Current specification in gemspec pins the jwt version to the latest released one, consequently setting an obstacle where users have to wait until twilio-ruby modifies gemspec and releases it in order to update jwt.

Although I truly appreciate that you are constantly updating this library, I think it would be better if it accommodates updating jwt independent of twilio-ruby. 

Also this change will

- start to run CI against newer version of jwt when it releases one, meaning if there is any unexpected breaking change, the CI can catch it ideally
- cut off chores like #372 and #626 until the next major update comes

As a reference which might help, oauth2 gem relies on jwt in this manner: https://rubygems.org/gems/oauth2

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-ruby/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Comment by shrutiburman** [comment]
Thanks for the PR! We've added the review to our backlog to be prioritised. Pull requests and +1s on the issue summary will help it move up the backlog.

**Comment by woodhull** [comment]
@shrutiburman I took a look and the diff in the jwt gem and it seems unlikely that loosening the dependency will cause any issues -- but it is blocking our use of the jwt gem version we'd like to use.

**Comment by alex-damian-negru** [comment]
Also closes https://github.com/twilio/twilio-ruby/issues/633; noticed the PR after creating the issue 👀

**Review by alex-damian-negru — APPROVED** [review]

**Comment by sealabcore** [comment]
🚀

**Review by childish-sambino — APPROVED** [review]

**Pull request merged**
