### PR TITLE
Remove holdovers from legacy library

### PR DESCRIPTION
**Pull request by dougblack**

### CODE REVIEW

**Comment by efossier** [comment]
@dougblack travis builds are failing

**Comment by Aesthetikx** [comment]
Is there a new recommendation for validating incoming requests, or should we simply check X-Twilio-Signature now that the middleware is gone?

**Comment by bartoszkopinski** [comment]
@dougblack @efossier Looks like `Twilio.configure` was removed here but it's still in the readme and there is nothing in the changelog about this change

**Comment by krmannix** [comment]
I'm also curious about the proper way to validate incoming requests. There doesn't seem to be much  documentation on the recommended process

**Comment by efossier** [comment]
@krmannix @bartoszkopinski @Aesthetikx Sorry for the confusion, we misidentifies this code as dead code. We'll be adding back the Rack middleware for signature validation. And `configure` functionality in future versions.

**Pull request merged**
