### PR TITLE
URI encode phone number lookups

### PR DESCRIPTION
**Pull request by philnash**
As reported in #153.

### CODE REVIEW

**Comment by skimbrel** [comment]
Would prefer we look into why our HTTP client isn't encoding all parameters correctly...

**Comment by philnash** [comment]
@skimbrel This isn't a parameter, it's part of the path. Until now we've only had SIDs in the path, which don't need extra encoding as they are just alphanumeric strings.

**Comment by skimbrel** [comment]
Ah, right. +1 then… but write a test.

**Comment by philnash** [comment]
How's that?

**Comment by skimbrel** [comment]
:+1:

**Pull request merged**
