### PR TITLE
chore: upgrade faraday to 1.0.0

### PR DESCRIPTION
**Pull request by juampi**

### CODE REVIEW

**Comment by jdarnok** [comment]
It's unfortunate that such updates are provided in the minor version of the minor version. We have so many dependencies issues caused by that (many gems locked their version of faraday to not reach 1.X), that it's way faster for us to just write curl requests for compliance API than resolving all that stuff.

**Comment by childish-sambino** [comment]
@jdarnok What's your recommendation here? Is it that major version upgrades to dependencies should result in major version rolls of this repo?

**Comment by magneland** [comment]
Hello!
I took a quick look at the changes for `faraday` v1.
Normally a major version bump is a big deal, but I believe what `faraday` mainly did was declare themselves no longer beta (after 10 years!).
See: https://github.com/lostisland/faraday/issues/903
and: https://github.com/lostisland/faraday/blob/master/CHANGELOG.md

As for this PR, I believe you could have done this instead: `spec.add_dependency('faraday', '>= '0.9', '< 2')`. I mean, you still can. This assumes `faraday` is both backwards and forwards compatible as far as its usage in this gem is concerned.
I do realize this gem is not exactly following semantic versioning either, but I would say that such a change would be consistent with a patch or minor version bump of this gem.

**Comment by magneland** [comment]
Oh and I just realized `faraday` v1 is not really backwards compatible:
https://github.com/lostisland/faraday/blob/master/UPGRADING.md
See the first paragraph there.

**Comment by jdarnok** [comment]
@childish-sambino Sorry for the late response. I think that @magneland suggestion for `spec` should be enough for now?

**Comment by childish-sambino** [comment]
Works for me. I can review/merge a PR if someone were to submit.

**Comment by jdarnok** [comment]
@magneland since you went with the idea, do you want to make that PR?
`spec.add_dependency('faraday', '>= '0.9', '< 2')`

**Comment by johnnyshields** [comment]
Hi, this update should **NOT** have been made in a tiny version. Ideally should be major version because it breaks the interface, but a minor version could arguably acceptable. Please refer to https://semver.org/

**Comment by Nucc** [comment]
Hi, we also have dependency issues and we can't get the latest regulatory bundle features because if this PR. Upgrading to Faraday 1.0 requires lots of changes in our codebase and also many gems support version ~>0.9 only because of changes in Faraday 1.0 like `WARNING: Unexpected middleware set after the adapter. This won't be supported from Faraday 1.0.`

Is Faraday 1.0 very required for the latest version? Can we revert this change and apply it in a major version fix?

**Comment by childish-sambino** [comment]
Fix submitted.

**Comment by magneland** [comment]
Sorry, I guess I jumped the ship early here. This looks good to me. I think my hesitation was with the changes to child error classes, but it looks like this gem only references `Faraday::Error` anyways.

Relevant change log comment:
```
Removes sub-class constants definition from Faraday::Error. A sub-class (e.g. ClientError) was previously accessible either through the Faraday module (e.g. Faraday::ClientError) or through the Faraday::Error class (e.g. Faraday::Error::ClientError). The latter is no longer available and the former should be used instead, so check your rescues.
```

**Pull request merged**
