### PR TITLE
chore: remove live media endpoint

### PR DESCRIPTION
**Pull request by califlower**
# Fixes #
remove twilio live media endpoint related to https://code.hq.twilio.com/twilio/api-definitions/pull/4055

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-ruby/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please file a [support ticket](https://twilio.com/help/contact), or create a GitHub Issue in this repository.

### CODE REVIEW

**Review by tiwarishubham635 — CHANGES_REQUESTED** [review]
Please remove [media.rb](https://github.com/califlower/twilio-ruby/blob/remove-media/lib/twilio-ruby/rest/media.rb), [media_base.rb](https://github.com/califlower/twilio-ruby/blob/remove-media/lib/twilio-ruby/rest/media_base.rb) and update client.rb like [this](https://github.com/califlower/twilio-ruby/blob/remove-media/lib/twilio-ruby/rest/client.rb#L86)

**Review by javierlopezfernandez — APPROVED** [review]

**Review by javierlopezfernandez — CHANGES_REQUESTED** [review]
I think lib/twilio-ruby/rest/media.rb needs to be removed too

**Review by javierlopezfernandez — APPROVED** [review]

**Comment by tiwarishubham635** [comment]
This test seems to fail, it says syntax [error](https://github.com/twilio/twilio-ruby/actions/runs/7715360457/job/21150110118?pr=710#step:9:11). Please check

**Review by tiwarishubham635 — APPROVED** [review]
LGTM

**Pull request merged**
