### PR TITLE
chore: update the user agent string for twilio-ruby

### PR DESCRIPTION
**Pull request by claudiachua**
Jira Issue: https://issues.corp.twilio.com/browse/DI-2050

### CODE REVIEW

**Comment by claudiachua** [comment]
run pr validation

**Review by childish-sambino — APPROVED** [review]

**Review by beebzz — APPROVED** [review]

**Review by makiRails — COMMENTED** [review]
I'm sorry. Would you please erase this comment?

**Comment by makiRails** [comment]
失礼しました。。誤投稿です。

**Comment by fschwahn** [comment]
This shells out twice, which seems a bit wasteful? Also, this looks as if it could cause cross-platform issues (ie. is `uname -m` supported on Windows?)

**Comment by claudiachua** [comment]
Hi [fschwahn](https://github.com/fschwahn), Thanks for pointing that out, I've put in a PR to the fix: https://github.com/twilio/twilio-ruby/pull/607

**Pull request merged**
