### PR TITLE
[dependencies/jwt] Bump version :jwt 1.0 -> 1.5

### PR DESCRIPTION
**Pull request by paulopatto**
Update dependencie JWT.

### CODE REVIEW

**Comment by IanConnolly** [comment]
Re: the rbx failure, capistrano moved rbx to allowed failures because of the same issue https://github.com/capistrano/capistrano/issues/1783

**Comment by IanConnolly** [comment]
@philnash do you/other Twilio folks have any ETA for taking a look at this?

**Comment by philnash** [comment]
Hey @IanConnolly, I'll get this in front of the API team. Thanks for calling this out.

**Comment by IanConnolly** [comment]
👍 thanks a bunch.

**Comment by tmconnors** [comment]
Included in our RC19 of the`next-gen` branch.

**Pull request closed without merging**
